server:
  port: 8082

spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Rs@3779030
    url: jdbc:mysql://localhost:3306/dcbapprod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: "Welcome to the Spring Boot application!"