server:
  port: 8082

spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Rs@3779030
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: "Welcome to the Spring Boot application!"


#welcome:
#  message: Welcome to Bangalore
#---
#spring:
#  profiles: qa
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: Rs@3779030
#    url: jdbc:mysql://localhost:3306/dcbappqa
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#welcome:
#  message: Welcome to Bangalore
#
#---
#
#spring:
#  profiles: prod
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: Rs@3779030
#    url: jdbc:mysql://localhost:3306/dcbappprod
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#welcome:
#  message: Welcome to Bangalore
